

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GOOGLE_LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GOOGLE_LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOADING_FAIL = 'LOADING_FAIL';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


export const RESTORE_TOKEN = 'RESTORE_TOKEN';
export const AUTH_ERROR = 'AUTH_ERROR';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_LOADED = 'USERS_LOADED';
